version: '3.4'

services:
  creation_ms:
    image: ${DOCKER_REGISTRY-}creationms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2307:2307"

  couchdb:
    image: couchdb:latest
    ports:
      - "5985:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=asdfg123
